### ISSUE TITLE
[BUG] Close tabs to right

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#1]
This closed a whole bunch of tabs that I had open, not just the ones to the right.

It seems to close tabs that were _more recently opened_ than the one I am on, regardless of their position left/right of the current tab.

I assume the same logic problem holds for "close to left", but I have not checked.

**Comment by otzbergnet** [comment]
Badly described feature :( it did what it was meant to do, but obviously I didn’t communicate it well. Translation update... will do

**Comment by gingerbeardman** [comment]
Ah, then I am not sure about use case for this feature?

**Comment by otzbergnet** [comment]
It is one of my habits, when I read an article, I often end up opening a whole bunch of links from that one article, click through them and then often end up closing them all one by one. I figured, well I could do that more easily. Closing just one on the left or right, would be less effort by clicking the x on that tab :) It might not be that useful - I admit

**Comment by gingerbeardman** [comment]
Yes, I also do that.

But I also might jump back/forth between the tabs opening new ones before I decide to close those unread news articles. Which will cause unexpected results (loss of tabs I wanted to keep) can appear.

**Comment by otzbergnet** [comment]
mmmh - I really quite like it :) I did update the label to state "Close all tabs on:" hoping to make that clearer :) Apple even has "Close all other tabs" feature, when you right click a tab. There is a whole lot of good stuff in Safari 13, for example tab sorting by title and website...

So what to do, do you think we could keep the feature for my personal entertainment, as long as it is sufficiently clear what it does.

I hope you didn't lose anything too vauable

**Comment by gingerbeardman** [comment]
I honestly can't remember what the tabs were, so it's easier to deal with the loss 😢

But nothing special.

I am wondering if you see the problem?

Here's a video: https://imgur.com/a/UpAltyv

**Comment by otzbergnet** [comment]
I need to take a moment to properly replicate this, but this looks bad :( Enough for me to want to review it properly and try to replicate

**Comment by otzbergnet** [comment]
OK that feature is utterly broken, as soon as you add a tab in the middle after the fact, which would be perfectly normal behavior :( - just not in my testing. Would be so lovely, if there was documentation in what order the array of tab objects is sorted. It obviously isn't the order the tabs are in.

I like the idea enough to poke at it some more, though

**Comment by gingerbeardman** [comment]
It must be possible because Tab Space does it (but it's not open-source)

**Comment by otzbergnet** [comment]
I set the extension to have website access permission to all pages and then watched the array that comes back.

The good news seems to be that the tabs do come back in the right order, which was my concern earlier. This does lead me to believe that a comparison of the proxy-objects is the completely false way to go. It also makes me wonder (there is still no tab-index) how Tab Spaces does do it :) I might just need to invest the €1,09 to see how much of what s/he does is JavaScript - I did however send her/him an eMail to see if maybe I can get a free lesson :)

So for now I would need to remove this feature, if I wanted to go to the AppStore right now :( Or I might keep at it some more. I think it is the latter for now...

Have a successful week!

Claus

**Comment by otzbergnet** [comment]
Just one more comment, it actually is incredibly trivial with Apple Script: 

close to left

tell window 1 of application "Safari"
	close (tabs where index < (get index of current tab))
end tell

It is kind of annoying that something can be so trivial in Apple Script and so "hard" in Swift (mostly since I don't really get how that API actually works yet)

**Comment by gingerbeardman** [comment]
Looking at the Tab Space extension, it's not done in JavaScript

**Comment by gingerbeardman** [comment]
Maybe some clues elsewhere on GutHub: https://github.com/search?utf8=✓&q=getAllTabs+language%3ASwift&type=Code&ref=advsearch&l=Swift&l=

**Comment by otzbergnet** [comment]
I actually think I figured it out last night, I just didn't commit it yet,
as I wanted to test it further. This morning I also got a hint from the
author of Tab Space, so I'll follow his short guidance to see where that
takes me :)

I did however confirm that:

a) The array is ordered
b) I had a pretty stupid logic error in my code
c) there has to be a better way

Greetings

Claus

**Comment by otzbergnet** [comment]
so I had an additional hint (the dev from the other extension we spoke about was most generous with his time), giving me a very solid hint. That hint taught me a marvelous new trick and simplified the logic. 

#5
