### ISSUE TITLE
[DISCUSS] Localization

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#11]
Just looking into this: https://github.com/Flinesoft/BartyCrouch

Could be an option to broaden localization for testing.

**Comment by otzbergnet** [comment]
Very interesting tool, need to read into it a bit and also try it out. Sounds like a fab project for now, considering how much effort I had to put in to find the new strings & labels, I really want to look into this :)

**Comment by otzbergnet** [comment]
I had a play with this today and it looks really quite promising. What I noticed is that it will require me to change my usual flow and that's not necessarily a problem.

bartycrouch will identify all "missing" translations from Localizable.strings, but ignores the Main.strings from the storyboard. This is NOT an issue, as in future projects I would be able to rather simply get started as usual and then swing over to Localizable.strings. I will need to play with this, but I will add to wbmExtension as well.

I'll close this for the moment
