### ISSUE TITLE
[DISCUSS] Open in Chrome / Opera / Firefox feature

### ISSUE THREAD

**Issue by otzbergnet** [otzbergnet/tabCount#15]
I was thinking that we could add one more button to the popover, which would force the current tab to open in Chrome / Opera / Firefox, or whatever the user activated in the Settings section of the containing app...

It is one of the things I tend to do from time to time, not sure it warrants a feature... what do you think?

**Comment by gingerbeardman** [comment]
I also do this. 

Currently I have two other extensions installed that offer this feature. 

I currently use this one:

Tab Space - provides shortcut keys to open in various browsers. 

Before that I used:

Switch Browser - provides an item in the Share menu that opens an awkward window. 

Regardless of all the time spent on the popover I don't think I'll ever personally open it!

**Comment by otzbergnet** [comment]
That's good to know, thinking about it, without changing the permissions I have no way of getting to the URL, so not one for the MVP.
