### ISSUE TITLE
[DISCUSS] Ideas

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#18]
Short cut to combine all windows?
- there's a Safari menu item for this

Tab Sorting
- sort by domain, grouped into windows
- remove duplicate tabs (new Safari avoids this by reopening already open tabs but does not address dupes already opened before that)
- previously used a different plugin [TabSort](https://www.diatomics.com/tabsorter/)

Not sure if these would complicate the simplicity of tabCount

**Comment by otzbergnet** [comment]
Some nice ideas, but I need to investigate what would be possible with our zero permissions approach, which we've taken - some stuff like sorting likely won't work :(

**Comment by gingerbeardman** [comment]
In that case, leave any such thing for potentially another extension.

**Comment by gingerbeardman** [comment]
I recently discovered you can right click a tab to get this menu:
![Screen shot 2020-01-07 at 11 36 45](https://user-images.githubusercontent.com/49612/71892872-0897f380-3142-11ea-98a9-782414949674.png)

Arrange by Title or Website.

So, with that and _Tab Space_ let's close this issue.

Want to do another extension? I've got a few ideas I will email.
