### ISSUE TITLE
One annoying thing about the current toolbar icon

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#24]
I dislike how the "tab corner" in the icon merges into the badge and makes its shape less discernible/readable.

<img width="44" alt="Screen shot 2021-05-14 at 11 13 40" src="https://user-images.githubusercontent.com/49612/118256773-c43f0500-b4a5-11eb-90fc-b5a38a823e87.png">

Am I correct that the old one was only abandoned due to lost artwork?

Would you be open to me creating a new icon that is a combination of the old one and the new one?

**Comment by otzbergnet** [comment]
Hi Matt,

yes, the icon was changed due to a lack of original artwork. Unfortunately, we now do need to consider whether changing it again is a great idea. I do hear your concerns though, so feel free to suggest a different icon and we can take it from there.

**Comment by gingerbeardman** [comment]
OK, I'll do something.

I think I mentioned in the past that the PDF artwork in the extension was as good as the original artwork (both vector files).

Anyway! I'll get on it.

**Comment by gingerbeardman** [comment]
How about simply removing the "tab" and shifting the hash upwards? Everything else remains the same. 

I would consider this a minor change, with minimal disruption. 

I'll create it soon

**Comment by otzbergnet** [comment]
Good Morning,

Just checking in on this one. No pressure - just want to know if you still want this change made? I will be honest, that I kind of like the logo, but I see your point about the badge covering the tab a bit in an not always pleasing way. I have my threshold set pretty high, so I see the logo as is most of the time only

**Comment by gingerbeardman** [comment]
I would still like to see it, yes.

But I had sensed your unwillingness, so I had not followed up on this issue.

One more thing I'm intrigued about - when the old logo art was needed, why did you create a new logo rather than recreating the old one? What was the motivation? No worries either way, I'm just interested in the rationale.

If you do want to change the logo, let me know and I'll get busy with a PR. Otherwise, I'll continue with my local build.

**Comment by otzbergnet** [comment]
I must apologise for having given you that impression. My main concern was that we need to change not just the toolbar icon, but the actual app icon as well. The rest, I am not so worried about... 

When redrawing the icon I basically was  going for what I considered simplicity, I am not much of a graphics person, I am really bad at it, so I went with what I thought looked like a browser with a tab and the hash symbol...

**Comment by gingerbeardman** [comment]
That's fine, no worries at all 😊

I'll put something together this week.

**Comment by gingerbeardman** [comment]
We can close this, now that I am compiling myself I changed the icon to my old one.

Cheers!
