### ISSUE TITLE
[REQ] Window count option

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#4]
In on of your prototypes I saw Tab count and window count.

![image](https://user-images.githubusercontent.com/49612/68087071-1d0df600-fe4a-11e9-9650-dce047e49e71.png)

I think this would be a useful user-configurable option.

But perhaps in the format where tab count is listed first:

<kbd>tabCount (windowCount)</kbd>

eg.
<kbd>123 (4)</kbd>
<kbd>123(4)</kbd>
<kbd>123/4</kbd>
<kbd>123-4</kbd>

**Comment by otzbergnet** [comment]
I added that option with a recent commit https://github.com/otzbergnet/tabCount/commit/bd7986a4e3fa5301c87cbe70261609bb9d6f0aa7 - I really need to remember to do feature branches, that I then merge in via a pull request. Sorry.

I need to test this through fully at first glance it does the job

**Comment by gingerbeardman** [comment]
I'm really fussy bout this and trying to find a good way to make window count appear separate to tab count.

How about superscript?

![Screen shot 2019-11-07 at 14 55 30](https://user-images.githubusercontent.com/49612/68399761-cf0d3100-016e-11ea-9fbf-b0798606d1b4.png)

Just about OK on my non-retina monitor, should be better on retina displays.

**Comment by otzbergnet** [comment]
So I had a quick play with this - screenshot with my 2012 iMac:

Double-Digit Tab / Single-Digit Window
![Bildschirmfoto 2019-11-07 um 17 07 17](https://user-images.githubusercontent.com/43129918/68406542-4e583000-0182-11ea-8a95-4bbd60000602.png)

Triple-Digit Tab / Double-Digit Window
![Bildschirmfoto 2019-11-07 um 17 12 24](https://user-images.githubusercontent.com/43129918/68406598-6334c380-0182-11ea-8fe5-75033006c67c.png)

I'd be cheating quite badly - using unicode characters for the badge, but I don't think that I could do an attributed string on the badge. What do you think?

**Comment by otzbergnet** [comment]
I think I would also want to add a rule to not show the window is 1, meaning the superscript would only start at 2. Wonder if that is too much inconsistency. What do you think?

**Comment by gingerbeardman** [comment]
I forgot to say that I added code for this locally, I used an answer on stackoverflow as a basis

```swift
    func updateCountBadge(){
        let showWindow = settings.getBoolData(key: "window")
        let maxTabs = settings.getIntData(key: "maxTabs")
        var badgeText = ""

		if(self.tabCount >= maxTabs){
            
            if(showWindow){
				badgeText = "\(self.tabCount) \(self.toSuperscript(i:self.windowCount))"	// — – : → ⋯ ▻
            }
            else{
                badgeText = "\(self.tabCount)"
            }
            
            SFSafariApplication.getActiveWindow { (window) in
                window?.getToolbarItem { $0?.setBadgeText(badgeText)}
            }
        }
    }
    
	// https://stackoverflow.com/a/52615045/28290
	func toSuperscript(i: Int) -> String {
		let powers : [String] = [
		  "\u{2070}",
		  "\u{00B9}",
		  "\u{00B2}",
		  "\u{00B3}",
		  "\u{2074}",
		  "\u{2075}",
		  "\u{2076}",
		  "\u{2077}",
		  "\u{2078}",
		  "\u{2079}"
		]

		let digits = Array(String(i))
		var string = ""

		for d in digits {
		  string.append("\(powers[Int(String(d))!])")
		}
		return string
	}
```

**Comment by otzbergnet** [comment]
I did the same thing, I merged it in :) #7

**Comment by gingerbeardman** [comment]
I always thought my fonts were not displaying correctly on my non-retina display using Mojave, so I just tweaked some things. Much better!

![Screen shot 2019-11-07 at 17 02 55](https://user-images.githubusercontent.com/49612/68410429-9a09da00-0180-11ea-96ec-f9785a0f27fc.png)

So a good result from this issue!

**Comment by gingerbeardman** [comment]
Window count text in popover will need to be changed to show Superscript

**Comment by otzbergnet** [comment]
I did that earlier - there should be a commit :) I noticed, while I was translating stuff...
