### ISSUE TITLE
[REQ] Tighten up the popover interface 

### ISSUE THREAD

**Issue by gingerbeardman** [otzbergnet/tabCount#8]
It feels a bit loose to me, and I think it's not needed to have the Extension name in there.

I'll make some changes soon.

Current:

![Screen shot 2019-11-08 at 15 52 56](https://user-images.githubusercontent.com/49612/68489871-de0fe400-023f-11ea-91e7-119f75ef699c.png)

**Comment by otzbergnet** [comment]
Thanks :)

**Comment by gingerbeardman** [comment]
I am not 100% satisfied with this yet so have not made any code changes, but thoughts appreciated.

My goal was to "simplify, simplify, simplify".

![Screen shot 2019-11-08 at 15 32 28](https://user-images.githubusercontent.com/49612/68488473-00ecc900-023d-11ea-8105-d580c01e80d4.png)

Changes:
- remove extension name
- regroup tab/window count/checkbox/threshold
- regroup close all tabs
- remove slider
- simplify/reduce number of words used

**Comment by otzbergnet** [comment]
I think you have something here, but you might also want to consider:

* If the layout is very tight in English, it likely will translate badly
into other languages or require a lot of flexibility in the layout. German
on average is 1/4 longer than English.
* So short is great, but it can create its own challenge
* If I were to look at this, I would not readily understand that the Tab
and Window Count is the actual Tab and Window Count

So imagine we had a clear Tab & Window Count above the settings section,
then we could remove the number from the settings and have an easier to
translate and understand UI.  Just a thought, happy to send you my idea for
such a layout later. It will add a bit of height to the window, but I think
it will be able to get close

**Comment by gingerbeardman** [comment]
- Good point about making count obvious. I did have them combined earlier "Tab Count: 123" but split them. 

- Please make it fit for German.

- Let's iterate!

I have just changed the screen/zip it for my "final" time.

**Comment by gingerbeardman** [comment]
I just realised you are replying by email so you would have only seen my first attempt and none of the many edits after that. Did you see count in it's own column?

**Comment by otzbergnet** [comment]
No. I’ll go online after exercise and take a peek. Sorry!

**Comment by otzbergnet** [comment]
Sorry for not going online first and thus critiquing without having seen everything. I get where you are coming from on your preferred design and agree that the counts are more obvious, but I still wonder, if we might be failing on glanceability.

I honestly don't have the answer here, I am just wondering. The more I look at your design the more I see its elegance, but I kind of would still want big numbers in this design. So ignore most everything in the below screenshot and just consider combining the large counts with your design.

Only other item to really consider is the "Close all tabs on". It'll be hard to squeeze a meaningful German label in there and thus I would want to propose dropping the buttons to the next line.

![Bildschirmfoto 2019-11-08 um 17 56 47](https://user-images.githubusercontent.com/43129918/68495812-44513280-0251-11ea-9be6-042611e0f002.png)

**Comment by gingerbeardman** [comment]
I see where you are coming from. Let's go with it.

The lack of alignment is driving me crazy 😜

But commit your changes and I will adjust 👍

**Comment by gingerbeardman** [comment]
Regarding close all tabs, would these make a difference to space used in German?

Close tabs, To Left, To Right

Close all tabs on, Left, Right

**Comment by otzbergnet** [comment]
> I see where you are coming from. Let's go with it.
> 
> The lack of alignment is driving me crazy 😜
> 
> But commit your changes and I will adjust 👍

I will work on that, they were very quick and very dirty changes. I will use your xib and work from there ;)

**Comment by otzbergnet** [comment]
> Regarding close all tabs, would these make a difference to space used in German?
> 
> Close tabs, To Left, To Right
> 
> Close all tabs on, Left, Right

German is a terrible language, as the verb would come at the end, but we can make it work. As I said, I'll start from your XIB and then you can align nicely. It also needs some additional tweaking on the code (more logic) - but we'll manage it!

**Comment by otzbergnet** [comment]
I just pushed a commit with the updated layout and associated logic. The layout is wanting of your tender-loving-care @gingerbeardman 

I need to test logic fully tomorrow, I can't help but feel that I screwed up somewhere

**Comment by otzbergnet** [comment]
Yup there was one really stupid decision in there. 

This case:
When the minimum tabCount wasn't met, but the windowCount was, I had previously decided to show both tabCount and windowCount to make for a nicer display. While testing it drove me bonkers, as it made no sense. I now changed it so that if both tab & window are to be shown, but tabCount isn't met, the windowCount will be shown as a superscript. that's not a great look, but it seems to make sense. The question should be, should it be superscript?

**Comment by gingerbeardman** [comment]
I think for consistency it should be.

Not ideal, but who really is going to count only windows?

**Comment by otzbergnet** [comment]
Just to confirm what will happen:

tabCount only - large number for tabCount
windowCount only - large number for windowCount
TabCount & Window Count - tabcount large, windowcount superscript, even if tabCount isn't shown due to threshold

**Comment by gingerbeardman** [comment]
So, Safari presents popover at 282px wide so it can't really be as tight as I have shown.

Now I need to figure out the right way to do autolayout constraints.

**Comment by gingerbeardman** [comment]
Thoughts...

- disable left/right buttons if on first/last tab
- why are the numbers in the combo boxes so low/near the edge? they are not in Xcode

![Screen shot 2019-11-10 at 16 38 30](https://user-images.githubusercontent.com/49612/68547356-88bb0a80-03d8-11ea-96fd-7d8e120ffd20.png)

**Comment by otzbergnet** [comment]
I like the new tighter layout:)

One question though - you declare different preferred content sizes? Shouldn't they be the same?

preferredContentSize = NSSize(width: 225, height: 283)
shared.preferredContentSize = NSSize(width:280, height:240)

**Comment by otzbergnet** [comment]
> Thoughts...
> 
> * disable left/right buttons if on first/last tab
> * why are the numbers in the combo boxes so low/near the edge? they are not in Xcode
> 
> ![Screen shot 2019-11-10 at 16 38 30](https://user-images.githubusercontent.com/49612/68547356-88bb0a80-03d8-11ea-96fd-7d8e120ffd20.png)

not sure why they would be so low
I'll work on the disabling for left / right

**Comment by gingerbeardman** [comment]
> One question though - you declare different preferred content sizes? Shouldn't they be the same?
> 
> preferredContentSize = NSSize(width: 225, height: 283)
> shared.preferredContentSize = NSSize(width:280, height:240)

You know, I am so tired I did not even see the first one that I could have just changed!

New PR incoming.

**Comment by gingerbeardman** [comment]
It kind of bugs me that there are two columns of same-sized things but I will live with it for a while.

**Comment by otzbergnet** [comment]
I have just added:

* disable left/right buttons if on first/last tab

Design: we can always iterate on this. I am starting to feel that we are in a decent place.

**Comment by gingerbeardman** [comment]
I think I like it without the boxes. Feels less cluttered.

![Screen shot 2019-11-10 at 18 27 27](https://user-images.githubusercontent.com/49612/68548724-0c302800-03e8-11ea-8e00-07023fd0e954.png)

At this point we are down to the minor details.

**Comment by otzbergnet** [comment]
Feel free to remove them boxes...

**Comment by gingerbeardman** [comment]
Will push changes soon. 

Do you get that weird, pale vertical line between the checkbox and "tabs" label? in Dark mode.

**Comment by gingerbeardman** [comment]
Merged

**Comment by otzbergnet** [comment]
> Will push changes soon.
> 
> Do you get that weird, pale vertical line between the checkbox and "tabs" label? in Dark mode.

No, I don't get that

**Comment by gingerbeardman** [comment]
Good, must just be a bug in Mojave to do with running a non-retina external screen.

**Comment by gingerbeardman** [comment]
My latest UI changes were a quick hack, I just made the boxes invisible. If we're cool with the new layout then they can be removed and I think we are pretty much "feature complete" for v1.0?
